# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_MMI_CHARGER)	+= mmi_charger/
obj-y				+= bm_adsp_ulog/
obj-$(CONFIG_QPNP_ADAPTIVE_CHARGE)	+= qpnp_adaptive_charge/
obj-$(CONFIG_QTI_GLINK_CHARGER)	+= qti_glink_charger/
